# Numpy libraries 

In [5]:
## Array in numpy
import numpy as np    # np is alias of numpy library
a = np.array([1,2,4,5])   # this is the one dimancinal array
print(a)

[1 2 4 5]


In [7]:
b = np.array([2,4,6,8])
print(b)
type(b)

[2 4 6 8]


numpy.ndarray

In [41]:
# Two dimension array
row1 = [2,4,6,8]
row2 = [1,3,5,7]
row3 = [1,3,4,6]
arr = np.array(row1)
arr1 = np.array([row1,row2,row3])
print(arr1)
arr.shape

[[2 4 6 8]
 [1 3 5 7]
 [1 3 4 6]]


(4,)

In [29]:
# Indexing in array
print(arr)

[2 4 6 8]


In [32]:
print(arr[0])
print(arr[1])

2
4


In [34]:
arr

array([2, 4, 6, 8])

In [35]:
arr[:-1]

array([2, 4, 6])

In [43]:
print(arr[::-1])
print(arr[::-2])
print(arr1)

[8 6 4 2]
[8 4]
[[2 4 6 8]
 [1 3 5 7]
 [1 3 4 6]]


In [49]:
arr1[:,1]   # all row of 1 column
arr1[1:,1]
arr1[1:,0]

array([1, 1])

In [63]:
 arr1[:,2]
arr1

array([[2, 4, 6, 8],
       [1, 3, 5, 7],
       [1, 3, 4, 6]])

In [62]:
arr1[1:,2:4]

array([[5, 7],
       [4, 6]])

In [72]:
arr1[0:,2:4]

array([[6, 8],
       [5, 7],
       [4, 6]])

In [75]:
## EDA point of view
arr[arr<6]

array([2, 4])

In [77]:
arr1.shape

(3, 4)

In [78]:
## reshape the array
arr1.reshape(4,3)

array([[2, 4, 6],
       [8, 1, 3],
       [5, 7, 1],
       [3, 4, 6]])

In [90]:
np.arange(0,11,2).reshape(3,1,2)

array([[[ 0,  2]],

       [[ 4,  6]],

       [[ 8, 10]]])

In [93]:
print(arr)
print(arr * arr)

[2 4 6 8]
[ 4 16 36 64]


In [95]:
np.zeros(3,4)

TypeError: Cannot interpret '4' as a data type

In [103]:
np.random.randint(10,50,4)

array([33, 41, 37, 15], dtype=int32)

In [104]:
np.random.random_sample((4,7))

array([[0.82509982, 0.11287838, 0.80150715, 0.24231688, 0.52037493,
        0.12936404, 0.21766089],
       [0.69187266, 0.60128516, 0.98456708, 0.07832039, 0.59259287,
        0.96937375, 0.75285782],
       [0.21213051, 0.00819505, 0.36408141, 0.74116501, 0.63393937,
        0.3003892 , 0.39326193],
       [0.5559123 , 0.17344149, 0.4424854 , 0.23396666, 0.0394092 ,
        0.30734194, 0.45460773]])