In [1]:
# create a Numpy array from a list and display its shape and data type
import numpy as np
arr1 = np.array([1,2,3,4,5,6,7,9,4,3,2])

In [3]:
print(arr1)
print(type(arr1))

[1 2 3 4 5 6 7 9 4 3 2]
<class 'numpy.ndarray'>


In [7]:
# crate a matrix of zeroes and ones with a given size
mat = np.eye(3,4)
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [8]:
# generate random numbers and find their sum and average
import random
import numpy as np

num_lst = np.arange(0,20,1)
random_num = random.randint(0,20)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [10]:
# Reshape a 1d array into a 2d matrix and print the new structure
arr1 = np.array([1,2,3,4,5,6,7,8])
arr2 = arr1.reshape(2,4)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [15]:
# Find mean median and standard deviation of a given dataset
data = np.array([1,2,5,7,12,10,14,17,10,15,18,20])
df_mean = np.mean(data)
df_median = np.median(data)
df_std = np.std(data)

In [16]:
print("mean ", df_mean)
print("median ", df_median)
print("Standard deviation ", df_std)

mean  10.916666666666666
median  11.0
Standard deviation  5.964594612284132


In [22]:
# perform matrix addition and multiplicaiton on two arrays
arr1 = np.array([[2,4,6],
                [0,4,8]])
arr2 = np.array([[1,3,5],
                [1,7,5]])
sum_arr = np.add(arr1, arr2)
print("sum ", sum_arr)
mul_arr = np.multiply(arr1, arr2)
print("Multiply ", mul_arr)

sum  [[ 3  7 11]
 [ 1 11 13]]
Multiply  [[ 2 12 30]
 [ 0 28 40]]


In [27]:
new_arr = data.reshape(3,4)
max_num = np.max(new_arr)
min_num = np.min(new_arr)
print(new_arr)
print("Maximum ", max_num)   
print("minimum ", min_num)

[[ 1  2  5  7]
 [12 10 14 17]
 [10 15 18 20]]
Maximum  20
minimum  1


In [32]:
# find row and column wise sum of array
row_wise = np.sum(new_arr, axis=1)
print(row_wise)
column_wise = np.sum(new_arr, axis=0)
print(column_wise)

[15 53 63]
[23 27 37 44]


In [30]:
# Normalization of the array 
arr3 = np.array([2,3,5,6,7,8,9])
normalize = (arr3 - np.min(arr3)) / (np.max(arr3) - np.min(arr3))
print(normalize)

[0.         0.14285714 0.42857143 0.57142857 0.71428571 0.85714286
 1.        ]
