# Numpy Libraries

In [1]:
import numpy as np

In [4]:
marks = [75,67,87,98,83,91,80]
print("List ",marks)

np_marks = np.array(marks)
print("Array ",np_marks)

List  [75, 67, 87, 98, 83, 91, 80]
Array  [75 67 87 98 83 91 80]


In [7]:
arr_2d = np.array([[1,2,3],
                  [3,4,5],
                  [6,7,8]])
print("2d Array ", arr_2d)

2d Array  [[1 2 3]
 [3 4 5]
 [6 7 8]]


# Multidimensional array

In [11]:
import numpy as np
matrix = np.array([[0,2,4],
                   [1,3,5],
                   [0,1,2]])
matrix


array([[0, 2, 4],
       [1, 3, 5],
       [0, 1, 2]])

In [13]:
# Zero value array
zero_arr = np.zeros((2,2))
zero_arr

array([[0., 0.],
       [0., 0.]])

In [14]:
# One Value array
ones_arr = np.ones((3,3))
ones_arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [2]:
import numpy as np
multi_arr = np.arange(0,11,2)  # 1 start number 2 end number 3 increament
multi_arr
# value_arr = np.array(multi_arr)
# value_arr

array([ 0,  2,  4,  6,  8, 10])

In [21]:
# Identity matrix
import numpy as np

id_matrix = np.eye(4)
id_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])