# Modification of Array

In [1]:
import numpy as np

In [6]:
arr_2d = np.array([[1,2,3],
                   [3,4,5]])
print(arr_2d.shape)   # define the size of array

(2, 3)


In [8]:
print(arr_2d.size)  # count number of element in array


6


In [12]:
arr1 = np.array([[[2,3],[3,4],[5,6]]])  # 3 dimension array

In [13]:
print(arr_2d.ndim) # present the dimension of array
print(arr1.ndim)  # present 3d array

2
3


In [15]:
arr2 = np.array([2.3,4.5,9,1])
print(arr2.dtype)   # represent the type of array 

float64


In [19]:
arr3 = np.array([3.6,2.9,1.9,2.7])
int_arr3 = arr3.astype(int)# convert any type of element in array
str_arr3 = arr3.astype(str)  # this make array in string type
print(int_arr3)
print(int_arr3.dtype)
print(str_arr3.dtype)

[3 2 1 2]
int64
<U32


# Airthmatic operation in Array

In [22]:
arr4 = np.array([10,20,30])
print(arr4+10)
print(arr4/5)
print(arr4-10)
print(arr4 ** 2)

[20 30 40]
[2. 4. 6.]
[ 0 10 20]
[100 400 900]


# Aggregation function

In [25]:
arr5 = np.array([[2,3,4],[4,6,8]])
print(np.sum(arr5))
print(np.mean(arr5))
print(np.min(arr5))
print(np.max(arr5))
print(np.std(arr5))   # find standard deviation
print(np.var(arr5))  # find varience

27
4.5
2
8
1.9790570145063195
3.9166666666666665


# Indexing in numpy

In [1]:
import numpy as np

In [10]:
arr = np.array([10,20,30,40,50,60])
print(arr) 
print(arr.dtype) # what kind of value store in array
print(arr[0]) 
print(arr[4])
print(arr[-5])

[10 20 30 40 50 60]
int64
10
50
20


# Slicing in Array

In [20]:
arr = np.array([12,23,14,17,19,20,26,28,25])
print(arr[0:5])
print(arr[-1:-6:-1])
print(arr[-1:-1-(len(arr)):-1])  # reverse the string
print(arr[1:6+1:])

[12 23 14 17 19]
[25 28 26 20 19]
[25 28 26 20 19 17 14 23 12]
[23 14 17 19 20 26]


# Fancy indexing

In [21]:
arr = np.array([12,23,14,17,19,20,26,28,25]) 
print(arr[[1,3,5,7]])

[23 17 20 28]


# Filtering data in array

In [25]:
arr = np.array([12,23,14,17,19,20,26,28,25])
print(arr[arr <= 20])

[12 14 17 19 20]


# Reshaping and manupulating array

In [28]:
arr = np.array([12,23,14,17,19,20,26,28,25,22,23,29])
reshape_arr = arr.reshape(3,4)
reshape_arr

array([[12, 23, 14, 17],
       [19, 20, 26, 28],
       [25, 22, 23, 29]])

# Flattering  array
1. .ravel() -> return view
2. .flatten() -> return copy

In [31]:
arr = np.array([[12,23,14],[17,19,20],[26,28,25]])
print(arr.ravel())
print(arr.flatten())


[12 23 14 17 19 20 26 28 25]
[12 23 14 17 19 20 26 28 25]
